// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sleep/{id}": {
            "get": {
                "description": "Retrieves sleep information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sleep"
                ],
                "summary": "Get sleep information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sleep ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Sleep"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Sleep": {
            "type": "object",
            "properties": {
                "createdTimestamp": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deepSleep": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "lightSleep": {
                    "type": "integer"
                },
                "rating": {
                    "type": "integer"
                },
                "remSleep": {
                    "type": "integer"
                },
                "totalSleep": {
                    "type": "integer"
                },
                "updatedTimestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
