definitions:
  main.GenericMessage:
    properties:
      message:
        type: string
    type: object
  main.Sleep:
    properties:
      createdTimestamp:
        type: string
      date:
        type: string
      deepSleep:
        type: integer
      id:
        type: string
      lightSleep:
        type: integer
      rating:
        type: integer
      remSleep:
        type: integer
      totalSleep:
        type: integer
      updatedTimestamp:
        type: string
    type: object
  main.Sleeps:
    properties:
      data:
        items:
          $ref: '#/definitions/main.Sleep'
        type: array
      next_token:
        type: string
      previous_token:
        type: string
    type: object
info:
  contact: {}
paths:
  /sleep/date/{date}:
    get:
      consumes:
      - application/json
      description: Retrieves sleep information with specified date
      parameters:
      - description: Date
        in: path
        name: date
        required: true
        type: string
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Sleep'
        "401":
          description: Unauthorized
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.GenericMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.GenericMessage'
      security:
      - ApiKeyAuth: []
      summary: Get sleep information by date
      tags:
      - sleep
  /sleep/id/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves sleep information with specified ID
      parameters:
      - description: Sleep ID
        in: path
        name: id
        required: true
        type: string
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Sleep'
        "401":
          description: Unauthorized
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.GenericMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.GenericMessage'
      security:
      - ApiKeyAuth: []
      summary: Get sleep information by ID
      tags:
      - sleep
  /sleep/list:
    get:
      description: |-
        Retrieves list of sleep information in descending order by date
        Specifying no query parameters pulls list starting with latest
        Caller can then specify a next_token or previous_token returned from
        calls to go forward and back in the list of items.  Only next_token OR
        previous_token should be specified.
      parameters:
      - description: next list search by next_token
        format: string
        in: query
        name: next_token
        type: string
      - description: previous list search by previous_token
        format: string
        in: query
        name: previous_token
        type: string
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Sleeps'
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.GenericMessage'
      security:
      - ApiKeyAuth: []
      summary: Get list of sleep information
      tags:
      - sleep
swagger: "2.0"
