definitions:
  main.Sleep:
    properties:
      createdTimestamp:
        type: string
      date:
        type: string
      deepSleep:
        type: integer
      id:
        type: string
      lightSleep:
        type: integer
      rating:
        type: integer
      remSleep:
        type: integer
      totalSleep:
        type: integer
      updatedTimestamp:
        type: string
    type: object
info:
  contact: {}
paths:
  /sleep/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves sleep information
      parameters:
      - description: Sleep ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Sleep'
      summary: Get sleep information
      tags:
      - sleep
swagger: "2.0"
